[package]
name = "w5500-ll"
version = "0.10.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"
rust-version = "1.56"
repository = "https://github.com/newAM/w5500-ll-rs"
license = "MIT"
description = "Low level driver for the Wiznet W5500 internet offload chip."
readme = "README.md"
keywords = ["spi", "driver", "embedded-hal-driver", "W5500", "wiznet"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/newAM/w5500-ll-rs"

[features]
std = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies.embedded-hal]
version = "0.2.4"
optional = true

[dependencies.defmt]
version = "0.3"
optional = true

[dev-dependencies]
embedded-hal-mock = "0.8"
version-sync = "0.9"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
