on:
  push:
  pull_request:
  schedule:
    - cron: "13 3 * * *"

name: CI

jobs:
  build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: RUSTFLAGS="-D warnings" cargo build --no-default-features
      - run: RUSTFLAGS="-D warnings" cargo build --no-default-features --features embedded-hal
      - run: RUSTFLAGS="-D warnings" cargo build --no-default-features --features std
      - run: RUSTFLAGS="-D warnings" cargo build --all-features
  
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --all-features

  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  format_check:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt -- --check

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo doc --no-default-features
      - run: cargo doc --no-default-features --features embedded-hal
      - run: cargo doc --no-default-features --features std
      - run: cargo doc --all-features

  rustdoc:
    name: rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: RUSTDOCFLAGS='--cfg docsrs' cargo +nightly rustdoc --all-features

  release:
    name: crates.io release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, test, clippy_check, format_check, doc, rustdoc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo publish --token ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
